#!/bin/bash

readonly ROOT_PATH=$GO_PATH/src/github.com/raonismaneoto/CustomDHT/
readonly CORE_PATH=$GO_PATH/src/github.com/raonismaneoto/CustomDHT/core
readonly CONTAINER_NAME=DHT-NODE-$RANDOM
readonly IMAGE_NAME=dht-node
readonly IMAGE_VERSION=latest
readonly IMAGE=$IMAGE_NAME:$IMAGE_VERSION
readonly PORT=$(grep ^NODE_PORT $CORE_PATH/.env | awk -F "=" '{print $2}')

build_image() {
    sudo docker build --no-cache --build-arg PORT_ARG=$1 -f core.Dockerfile -t raonismaneoto/$IMAGE .
}

setup_container_image() {
    sudo docker pull raonismaneoto/$IMAGE
}

start() {
    echo $PORT
    sudo docker stop $CONTAINER_NAME
    sudo docker rm $CONTAINER_NAME
    sudo docker run --name $CONTAINER_NAME -p $PORT:$PORT --env-file $CORE_PATH/.env -idt raonismaneoto/$IMAGE
}

main() {
    cd $ROOT_PATH
    [[ -n $1 ]] && [[ "$1" == "--build-image" ]] && build_image $PORT
    [[ -z $1 ]] || [[ "$1" != "--build-image" ]] && setup_container_image
    start
}

main $@