#!/bin/bash

readonly ROOT_PATH=$GO_PATH/src/github.com/raonismaneoto/CustomDHT/
readonly API_PATH=$GO_PATH/src/github.com/raonismaneoto/CustomDHT/api
readonly CONTAINER_NAME=DHT-API
readonly IMAGE_NAME=dht-api
readonly IMAGE_VERSION=latest
readonly IMAGE=$IMAGE_NAME:$IMAGE_VERSION
readonly PORT=$(grep ^PORT $API_PATH/.env | awk -F "=" '{print $2}')


build_image() {
    sudo docker build --no-cache --build-arg PORT_ARG=$PORT -f api.Dockerfile -t raonismaneoto/$IMAGE .
}

setup_container_image() {
    sudo docker pull raonismaneoto/$IMAGE
}

start() {
    sudo docker stop $CONTAINER_NAME
    sudo docker rm $CONTAINER_NAME
    sudo docker run --name $CONTAINER_NAME -idt -p $PORT:$PORT --env-file $API_PATH/.env raonismaneoto/$IMAGE
}

main() {
    cd $ROOT_PATH
    [[ -n $1 ]] && [[ "$1" == "--build-image" ]] && build_image
    [[ -z $1 ]] || [[ "$1" != "--build-image" ]] && setup_container_image
    start
}

main $@